name: Sync Repository

on:
  workflow_dispatch: # 手动触发
  schedule:          # 或者定期同步，比如每天凌晨同步
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 克隆别人的仓库
      - name: Clone source repository
        uses: actions/checkout@v3
        with:
          repository: USTCCB/RainbowLight
          ref: master  # 选择分支
          path: source-repo

      # 初始化目标仓库为 Git 仓库
      - name: Prepare target repository
        run: |
          mkdir target-repo
          cd target-repo
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add origin https://github.com/USTCCB/USTCCB.GitHub.io.git
          cd ..

      # 将文件从源仓库复制到目标仓库
      - name: Copy files
        run: |
          cp -r source-repo/前端源码/version5.0/* target-repo/

      # 提交并推送到目标仓库
      - name: Push to target repository
        run: |
          cd target-repo
          git add .
          git commit -m "Sync files from source repository"
          git branch -M main
          git push -u origin main
